apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: add-dep
spec:
  replicas: 2
  template: 
    metadata:
      labels:
        app: add-app
    spec:
      containers:
      - name: add-container
        image: jenkins
        ports:
        - containerPort: 8080
