apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-dep
spec:
  replicas: 10
  template: 
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: sp-container
        image: nginx
        ports:
        - containerPort: 80
