apiVersion: v1
kind: Service
metadata:
  name: my-service-lb
  labels:
    service: my-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    nodePort: 31222
    protocol: TCP
  selector:
    app: my-app
