apiVersion: v1
kind: Service
metadata:
  name: my-service-lb2
  labels:
    service: my-service2
spec:
  type: LoadBalancer
  ports:
  - port: 80
    nodePort: 31223
    targetPort: 8080
    protocol: TCP
  selector:
    app: add-app
